version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client-build
    volumes:
      - ./client:/app/client
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-build
    volumes:
      - ./server:/app/server
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development